name: "Build"

on:
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        working-directory: ./packages/theme
        run: yarn install --frozen-lockfile

      - name: Build
        working-directory: ./packages/theme
        run: yarn build
